// This file is generated by scripts/generate-photo-manifest.mjs.
// Do not edit it manually. Add photos to public/photos instead.

export type PhotoItem = {
  src: string
  file: string
  slug: string
  title: string
  alt: string
  date: string
  place: string
  excerpt: string
  contentHtml: string
  sortKey: string
}

export const photos: PhotoItem[] = [
  {
    "src": "photos/2025-12-05-welcome-nana.jpg",
    "file": "2025-12-05-welcome-nana.jpg",
    "slug": "2025-12-05-welcome-nana",
    "title": "欢迎娜娜加入我们家",
    "alt": "欢迎娜娜加入我们家的照片",
    "date": "2025-12-05",
    "place": "",
    "excerpt": "欢迎娜娜加入我们家。",
    "contentHtml": "<p>欢迎娜娜加入我们家。</p>",
    "sortKey": "2025-12-05"
  }
]
